# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: sync output 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Sync output to _site
    runs-on: ubuntu-latest
    environment: stage
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:

      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # bundler-cache automatically installs gems
          bundler-cache: true
          cache-version: 1
      
      - name: Install node.js.
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install NPM dependencies.
        shell: bash
        run: npm install
        
      - name: Package site
        run: bundle exec ./bin/bridgetown deploy

      - name: Create and sync _site
        run: mkdir -p _site && cp -r output/* _site/
        
      - name: Push to production branch
        run: |
          git config --global user.name "Davida Marion"
          git config --global user.email "davida.marion@gsa.gov"
          git commit -am "Site build"
          git push prod